apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web #can be any value
spec:
  containers:
    - name: client
#      image: stephengrider/multi-client
      image: stephengrider/multi-worker
      ports:
        - containerPort: 3000