version: "3"
services:
  postgres:
    image: "postgres:latest"

  redis:
    image: "redis:latest"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on: 
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DB=postgres
      - PG_PASSWORD=admin

  client:
    build:
      context: "./client"
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
      
  worker:
    build:
      context: "./worker"
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
      
  nginx:
    restart: always
    build:
      context: "./nginx"
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
      - worker
    ports:
    - "3050:80"
