version: "3.0"

networks:
  default:
    driver: bridge

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - default
    ports:
      - "5432:5432"

  redis:
    image: "redis:latest"
    networks:
      - default

  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on: 
      - redis
      - postgres
    networks:
      - default
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DB=postgres
      - PG_PASSWORD=admin

  client:
    build:
      context: "./client"
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
      
  worker:
    build:
      context: "./worker"
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - default
    volumes:
      - /app/node_modules
      - ./worker:/app
      
  nginx:
    restart: always
    build:
      context: "./nginx"
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
      - worker
    ports:
    - "3050:80"
